### ISSUE TITLE
Consider creating a gem so that this package can be required in sass/compass

### ISSUE THREAD

**Issue by ghost** [microcipcip/gridy#3]
This is not a real issue, but since it's built in sass, you should build a gem so that we (users) can install it via ruby and require it in our sass file

**Comment by microcipcip** [comment]
Sorry I don't know how to create one, I stopped using Ruby and Compass few years ago. If you know of any tutorial I can follow I can try adding it, but only if it is not too time consuming.

**Comment by microcipcip** [comment]
I am closing this for now, let me know if you have a easy solution to integrate this in a gem.

**Comment by ghost** [comment]
As soon as I have some spare time I will!

Il 01 set 2017 11:50, "Salvatore Tedde" <notifications@github.com> ha
scritto:

**Comment by microcipcip** [comment]
Grazie ;)
